### ISSUE TITLE
Cannot read property 'lastmodified' of undefined

### ISSUE THREAD

**Issue by linoth** [Tibowl/KCCacheProxy#10]
**Describe the bug**
I cannot begin to tell you exactly why this happens; it just does, seemingly arbitrarily.

The proxy, running on either Win 10 or Ubuntu 18.04.4, either version 2.5.0 or 2.5.1, will throw the following error for a file, and I did not really notice a pattern in which ones:

> Loading... /kcs2/resources/slot/btxt_flat/106_9125.png
> (node:21758) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'lastmodified' of undefined
>     at getModified (/snapshot/CacheProxy/src/proxy/mod/patcher.js)
>     at patch (/snapshot/CacheProxy/src/proxy/mod/patcher.js)
>     at async send (/snapshot/CacheProxy/src/proxy/cacher.js)
>     at async Object.handleCaching (/snapshot/CacheProxy/src/proxy/cacher.js)
>     at async Server.<anonymous> (/snapshot/CacheProxy/src/proxy/proxy.js)
> (node:21758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise w
> (node:21758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero e
> Saved http://125.6.189.71/kcs2/resources/slot/btxt_flat/106_9125.png?version=2

**To Reproduce**
1. Start up KanColle running through KCCacheProxy with a mod freshly installed (I used the English Patch)
2. Play as normal and watch the log.
3. Error message will probably come up eventually.

**Expected behavior**
Lack of error, patched content gets loaded and delivered to the client...

**Desktop (please complete the following information):**
 - Proxy running on Windows 10 and Ubuntu 18.04.4
 - KCCacheProxy version 2.5.0 and 2.5.1

**Additional context**
KanColle will sometimes "freeze up" because the asset never comes.  Restarting the proxy can fix this.  Sometimes it doesn't freeze though.  I could not tell if any attempt was made to load patched content afterward.  I set the proxy to preload on start-up to see if that might correct the trouble, but I do not believe that it did so.

**Comment by Tibowl** [comment]
That was caused by patching files which aren't in general cache (some metadata is missing which gets saved after writing file to disk to prevent some race-conditions). Will be solved by waiting for file gets written to disk before patching it. Saving metadata before writing file could cause some other issues and passing it through would be messy. 

Will be fixed in v2.5.2

**Comment by Giocovier** [comment]
Still seeing issue in a minimally cached fresh install. 

`22:36:41.600: (node:24140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
22:36:41.600: (node:24140) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getBufferAsync' of undefined
at getModified (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\mod\patcher.js:155:77)
at async patch (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\mod\patcher.js:118:12)
at async send (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\cacher.js:271:20)
at async Object.handleCaching (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\cacher.js:341:20)
at async Server.<anonymous> (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\proxy.js:35:12)`

Reproduction - On any page update such as expedition complete, newly constructed ship, etc. 

Have tested with minimal cache, bypass disabled (using KC3 gadget by pass in lieu), browsing cachigng is enabled and not overwriting game version. Same issue occurs with full cache + diff downloaded. 

Eventually the request will time out (120 seconds looks like) and the asset will get requested to server, saved, and cache updated. 

Timeout example; 

`22:44:22.388: Saved cached to B:\kancolle-cache\cached.json.
22:44:17.373: Saved http://203.104.209.150/kcs/sound/kcjiftwdxqwtin/139240.mp3?version=11
22:44:16.821: Loading... /kcs/sound/kcjiftwdxqwtin/139240.mp3
22:44:16.821: GET: http://203.104.209.150/kcs/sound/kcjiftwdxqwtin/139240.mp3?version=11
22:44:15.715: Saved cached to B:\kancolle-cache\cached.json.
22:44:10.704: Saved http://203.104.209.150/kcs2/img/common/ship_bg/screen/c2.png
22:44:09.075: Loading... /kcs2/img/common/ship_bg/screen/c2.png
22:44:09.075: GET: http://203.104.209.150/kcs2/img/common/ship_bg/screen/c2.png
22:42:15.009: Saved cached to B:\kancolle-cache\cached.json.
22:42:10.077: (node:24140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
22:42:10.077: (node:24140) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getBufferAsync' of undefined
at getModified (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\mod\patcher.js:155:77)
at async patch (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\mod\patcher.js:118:12)
at async send (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\cacher.js:271:20)
at async Object.handleCaching (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\cacher.js:365:12)
at async Server.<anonymous> (C:\Users\giova\AppData\Local\KCCacheProxy\app-2.6.1\resources\app\src\proxy\proxy.js:35:12)
22:42:09.995: Need to repatch /kcs2/resources/ship/full/0100_4684_jiftwdxqwtin.png
22:42:09.994: Saved http://203.104.209.150/kcs2/resources/ship/full/0100_4684_jiftwdxqwtin.png?version=59
22:42:08.723: Loading... /kcs2/resources/ship/full/0100_4684_jiftwdxqwtin.png
22:42:08.723: GET: http://203.104.209.150/kcs2/resources/ship/full/0100_4684_jiftwdxqwtin.png?version=59`

Asset is not displayed correctly ;
![image](https://user-images.githubusercontent.com/6348757/91515385-0fcd6680-e8b7-11ea-8cc2-cfc700f4d1ee.png)

Let me know if you want me to reproduce anything or if you've got a debug mode hidden somewhere to kick out some additional info. I'd love to see this up and working smoothly so I can force Bep's fall outfit year round!

**Comment by Tibowl** [comment]
Was caused by some patches not matching original image file, will be fixed in v2.6.2.
