### ISSUE TITLE
Can't log in game after cleared cookies

### ISSUE THREAD

**Issue by wenyongzhe1992** [Tibowl/KCCacheProxy#8]
Hi. I used to be able to log in the game using the software. However, yesterday after cleared Chrome cookies, I was not able to log in any more. It says "the game is not available in your region". I tried to reinstall the software and the SwitchOmegaProxy, but it didn't work...

**Comment by Tibowl** [comment]
The proxy bypasses the KanColle gadget IP block, it doesn't bypass the DMM cookie check. See [wiki](https://kancolle.fandom.com/wiki/Tutorial:_Connection#General_DMM_Cookie-based_Block) for more information

**Comment by wenyongzhe1992** [comment]
Thank you very much, I didn't know I have to bypass the DMM check separately.
