### ISSUE TITLE
KCCacheProxy attempts to use missing mod-cache.json

### ISSUE THREAD

**Issue by linoth** [Tibowl/KCCacheProxy#9]
**Describe the bug**
mod-cache.json is not automatically generated.

**To Reproduce**
Enable mods for the first time, see the log telling you that it's loading things from cache/mod-cache.json.  That file doesn't exist and won't.  Not sure how many of my issues were caused by that.

**Expected behavior**
Probably either include the empty file in the source/build, or generate a new one on demand.

**Desktop (please complete the following information):**
 - KCCacheProxy running on Windows 10, and also Ubuntu 18.04.4
 - KCCacheProxy 2.5.0 and 2.5.1 both had trouble with this on both systems.

**Additional context**
Creating a file containing just "{}" circumvents this problem, as KCCacheProxy will happily use the now-existing, valid JSON file.

**Comment by Tibowl** [comment]
Shouldn't cause issues since it will fall back to an empty mod cache. File will be created after first save.
I'll make that a bit more clear in v2.5.2
